// @ts-nocheclk
import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    tags: ["bestSeller", "DSA"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: true,
    rating: 3.5,
    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["bestSeller", "OS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: true,
    rating: 3.5,

    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["bestSeller", "OS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: true,
    rating: 0.5,
    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["bestSeller", "DBMS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: true,
    rating: 5.0,

    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["DBMS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: false,
    rating: 3.5,
    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["OS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: false,
    rating: 2.5,
    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["DBMS"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: false,
    rating: 1.5,
    sellerId: "111",
  },
  {
    id: uuid(),
    tags: ["DSA"],
    publisher: "Pegion",
    name: "Introduction to Algorithms, third edition",
    author: "Thomas H. Cormen",
    image: "https://log2.netlify.app/assets/jpgs/coremen.jpg",
    imgAlt: "image link",
    description:
      "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum  ",
    discountPrice: 749,
    price: 999,
    discount: 25,
    inStock: true,
    rating: 1.5,
    sellerId: "111",
  },
];
